[settings]
provider = "kubernetes"

[relaychain]
chain = "rococo-local"
default_command = "polkadot"
default_image = "docker.io/parity/polkadot:1.0.0"
default_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1
chain = "local"

  [parachains.collator]
  name = "paraA-collator"
  command = "polkadot-parachain"
  image = "docker.io/parity/polkadot-parachain:1.0.0"
  args = ["-lparachain=debug", "--chain=contracts-rococo"]

[[parachains]]
id = 2
chain = "local"

  [parachains.collator]
  name = "paraB-collator"
  command = "polkadot-parachain"
  image = "docker.io/parity/polkadot-parachain:1.0.0"
  args = ["-lparachain=debug", "--chain=contracts-rococo"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

[[hrmp_channels]]
sender = 1
recipient = 2
max_capacity = 8
max_message_size = 10240

[[hrmp_channels]]
sender = 2
recipient = 1
max_capacity = 8
max_message_size = 10240